api_platform:
    mapping:
        paths: [
            '%kernel.project_dir%/src/Infrastructure/User/ApiPlatform/Resource/',
        ]
    patch_formats:
        json: [
            'application/merge-patch+json'
        ]
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    exception_to_status:
        Webmozart\Assert\InvalidArgumentException: 422
