doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        default_entity_manager: default
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/User/Model'
                prefix: 'App\Domain\User\Model'
                alias: 'User'
            JWTToken:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/JWTToken/Model'
                prefix: 'App\Domain\JWTToken\Model'
                alias: 'JWTToken'
            Currency:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Currency/Model'
                prefix: 'App\Domain\Currency\Model'
                alias: 'Currency'
#            Inventory:
#                is_bundle: false
#                type: attribute
#                dir: '%kernel.project_dir%/src/Domain/Inventory/Model'
#                prefix: 'App\Domain\Inventory\Model'
#                alias: 'Inventory'
            Purchase:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Purchase/Model'
                prefix: 'App\Domain\Purchase\Model'
                alias: 'Purchase'
