# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    php_errors:
        log: 4096
    test: true
    serializer:
        default_context:
            enable_max_depth: true
            yaml_indentation: 2