framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus: []
            query.bus: []
        transports:
            sync: sync://
        routing:
            App\Domain\Shared\Query\QueryInterface: sync
            App\Domain\Shared\Command\CommandInterface: sync
        reset_on_message: true
