when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

api_platform:
    resource: .
    type: api_platform
    prefix: /api
login:
    path: /authentication_token
refresh_token:
    path: /authentication_token/refresh