parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $cryptoApiUrl: '%env(string:MAIN_API_URL)%'
            $cryptoApiUrlGetAll: '%env(string:MAIN_API_URL_GET_ALL)%'
            $dolarRatioApiUrl: '%env(string:USD_RATIO_API)%'

    App\:
        resource: '../../src/'
        exclude:
            - '../../src/Infrastructure/Shared/Kernel.php'

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    App\Infrastructure\Currency\Service\CryptoCurrencyDataDownloadService:
        arguments:
            $client: '@monolog.http_client'