parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../../src/'
        exclude:
            - '../src/Infrastructure/Shared/Kernel.php'

    App\Infrastructure\User\ApiPlatform\State\Provider\UserCrudProvider:
        tags:
            - { name: 'api_platform.state_provider', priority: 0 }

    App\Infrastructure\User\ApiPlatform\State\Processor\UserCrudProcessor:
        tags:
            - { name: 'api_platform.state_provider', priority: 0 }

    App\Domain\User\Repository\UserRepositoryInterface:
        class: App\Infrastructure\User\Doctrine\DoctrineUserRepository
